{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_sample.py:7: AssertionError"}, "start": 1700150376712, "stop": 1700150376712, "uuid": "2ccc4151-055c-4ec8-8a79-91c9d56640ba", "historyId": "c398165193b396d834e5e030605bc655", "testCaseId": "c398165193b396d834e5e030605bc655", "fullName": "test_sample#test_answer", "labels": [{"name": "suite", "value": "test_sample"}, {"name": "host", "value": "NL_J5J6GD4V0H"}, {"name": "thread", "value": "69216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}